#!/bin/bash

# Exit on any command failure
set -e

# Run Prettier for backend
cd server || exit 1
npm run format || { echo 'Backend Prettier failed'; exit 1; }

# Run Prettier for client
cd ../web || exit 1
npm run format || { echo 'Client Prettier failed'; exit 1; }

# Run Prettier for mobile
cd ../mobile || exit 1
npm run format || { echo 'Mobile Prettier failed'; exit 1; }
